//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Activity
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Activity()
    {
        this.ApprovalDisapprovals = new HashSet<ApprovalDisapproval>();
        this.VotedBies = new HashSet<VotedBy>();
        this.Comments = new HashSet<Comment>();
    }

    public int activity_id { get; set; }
    public string activity_name { get; set; }
    public System.DateTime activity_date { get; set; }
    public string activity_description { get; set; }
    public int total_approval { get; set; }
    public int studet_id { get; set; }
    public int vote { get; set; }
    public string activity_type { get; set; }
    public bool isActive { get; set; }
    public int total_dissapproval { get; set; }
    public Nullable<System.DateTime> addedDate { get; set; }
    public string comment { get; set; }

    public virtual StudentInformation StudentInformation { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ApprovalDisapproval> ApprovalDisapprovals { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VotedBy> VotedBies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
}

public partial class ApprovalDisapproval
{
    public int id { get; set; }
    public int student_id { get; set; }
    public int activity_id { get; set; }
    public Nullable<bool> approval { get; set; }
    public Nullable<bool> disapproval { get; set; }

    public virtual StudentInformation StudentInformation { get; set; }
    public virtual Activity Activity { get; set; }
}

public partial class Comment
{
    public int id { get; set; }
    public int student_id { get; set; }
    public int activity_id { get; set; }
    public string comment1 { get; set; }

    public virtual Activity Activity { get; set; }
    public virtual StudentInformation StudentInformation { get; set; }
}

public partial class StudentInformation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public StudentInformation()
    {
        this.ApprovalDisapprovals = new HashSet<ApprovalDisapproval>();
        this.VotedBies = new HashSet<VotedBy>();
        this.Activities = new HashSet<Activity>();
        this.Comments = new HashSet<Comment>();
    }

    public int studentId { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string birthDate { get; set; }
    public string email { get; set; }
    public string department { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public byte[] photo { get; set; }
    public bool isAdmin { get; set; }
    public bool isActive { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ApprovalDisapproval> ApprovalDisapprovals { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VotedBy> VotedBies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Activity> Activities { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class VotedBy
{
    public int id { get; set; }
    public int student_id { get; set; }
    public int activity_id { get; set; }
    public int vote { get; set; }

    public virtual StudentInformation StudentInformation { get; set; }
    public virtual Activity Activity { get; set; }
}
