//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TermProjectEntities : DbContext
{
    public TermProjectEntities()
        : base("name=TermProjectEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ApprovalDisapproval> ApprovalDisapprovals { get; set; }
    public virtual DbSet<StudentInformation> StudentInformations { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<VotedBy> VotedBies { get; set; }
    public virtual DbSet<Activity> Activities { get; set; }
    public virtual DbSet<Comment> Comments { get; set; }
}
